# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

require 'google/protobuf'


descriptor_data = "\n\rgreeter.proto\x12\x07greeter\"+\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05times\x18\x02 \x01(\x05\",\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\x32\x80\x01\n\x07Greeter\x12\x38\n\x08SayHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\"\x00\x12;\n\tCountDown\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\"\x00\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Greeter
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greeter.HelloReply").msgclass
end
